"""2021_08_11_15_48_55

Revision ID: 9f12bfac7121
Revises: c45da1060132
Create Date: 2021-08-11 15:48:56.674832

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '9f12bfac7121'
down_revision = 'c45da1060132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('others')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('others', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
