"""2021_08_11_15_41_53

Revision ID: c45da1060132
Revises: f3b56558f436
Create Date: 2021-08-11 15:41:54.186374

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'c45da1060132'
down_revision = 'f3b56558f436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('others', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'others')
    # ### end Alembic commands ###
